name: data_rerun

services:
  data_rerun:
    build:
      context: ../..
      dockerfile: docker_for_train/Dockerfile
      args:
        CUDA_IMAGE: ${CUDA_IMAGE:-docker.m.daocloud.io/nvidia/cuda}
        CUDA_TAG: ${CUDA_TAG:-12.4.1-cudnn-devel-ubuntu22.04}
        CUDA_RUNTIME_TAG: ${CUDA_RUNTIME_TAG:-12.4.1-cudnn-runtime-ubuntu22.04}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
        USER_ID: ${LOCAL_UID:-1000}
        GROUP_ID: ${LOCAL_GID:-1000}
    image: dp-hirol:train
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    working_dir: /workspace
    command: sleep infinity
    stdin_open: true
    tty: true
    ipc: host
    gpus: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
       MUJOCO_GL: osmesa
       WANDB_DIR: /workspace/wandb
       MPLCONFIGDIR: /tmp/matplotlib
       PYTHONPATH: /workspace
       DISPLAY: ${DISPLAY}
       XAUTHORITY: /tmp/.docker.xauth
       NVIDIA_VISIBLE_DEVICES: all
       NVIDIA_DRIVER_CAPABILITIES: all
       WINIT_UNIX_BACKEND: x11
       WGPU_BACKEND: vulkan
       SDL_VIDEODRIVER: x11
       SDL_AUDIODRIVER: pulse
       UDEV: "1"
    volumes:
      - ../..:/workspace
      - ../../../data:/workspace/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # 给容器访问宿主机的X11权限
      - ${XAUTHORITY:-$HOME/.Xauthority}:/tmp/.docker.xauth:ro
