name: dp-hirol

services:
  trainer:
    build:
      context: ..
      dockerfile: docker_for_train/Dockerfile
      args:
        CUDA_IMAGE: ${CUDA_IMAGE:-docker.m.daocloud.io/nvidia/cuda}
        CUDA_TAG: ${CUDA_TAG:-12.4.1-cudnn-devel-ubuntu22.04}
        CUDA_RUNTIME_TAG: ${CUDA_RUNTIME_TAG:-12.4.1-cudnn-runtime-ubuntu22.04}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
        USER_ID: ${LOCAL_UID:-1000}
        GROUP_ID: ${LOCAL_GID:-1000}
    image: dp-hirol:train
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    working_dir: /workspace
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
       MUJOCO_GL: osmesa
       WANDB_DIR: /workspace/wandb
       MPLCONFIGDIR: /tmp/matplotlib
       PYTHONPATH: /workspace
       DISPLAY: ${DISPLAY}
       XAUTHORITY: ${XAUTHORITY:-$HOME/.Xauthority}
      #  HTTP_PROXY: ${HTTP_PROXY:-}
      #  HTTPS_PROXY: ${HTTPS_PROXY:-}
      #  NO_PROXY: ${NO_PROXY:-}
      #  http_proxy: ${http_proxy:-}
      #  https_proxy: ${https_proxy:-}
      #  no_proxy: ${no_proxy:-}
       SDL_VIDEODRIVER: x11
       SDL_AUDIODRIVER: pulse
       UDEV: "1"
    volumes:
      - ..:/workspace
      - ../../data:/workspace/data
      - ../outputs:/workspace/outputs
      - ../data_converter/dataset:/workspace/data_converter/dataset
